language: node_js
node_js: "v14.3.0"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  # - mysql -e 'CREATE DATABASE b5w8fpklr409oa7q;'
script: echo "npm test temporarily disabled"
